# GitHub Review Bot Configuration

# Required: Repository type
type: frontend  # Since this is a Next.js app

# Required: Review strictness level
strictness: medium  # Options: low, medium, high

# Optional: Custom rules
rules:
  # Enable/disable specific checks
  code_style: true
  security: true
  documentation: true
  tests: true
  performance: true

  # Custom thresholds
  min_test_coverage: 80
  max_file_size_kb: 100
  max_complexity: 10

# Next.js specific settings
nextjs:
  check_app_directory: true
  check_image_optimization: true
  check_metadata: true
  check_api_routes: true
  check_middleware: true

# Vercel specific settings
vercel:
  check_vercel_json: true
  check_environment_vars: true
  check_build_settings: true

# Optional: Custom messages
messages:
  approval: "✅ All checks passed! Great work!"
  request_changes: "⚠️ Please address the following issues:"
  error: "❌ Critical issues found that must be fixed:"